### ISSUE TITLE
installation issue with placer

### ISSUE THREAD

**Issue by suskraem** [ericcapo/marky-coco#1]
Hello,
I'm trying to install marky-coco on a Macbook Pro (Monterey OS) but have an issue with pplacer in the conda environment:
 
marky-coco % conda env create -f environment.yml       
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - pplacer

I installed placer separately and added it to the path, but this doesn't solve the issue. Any help is greatly appreciated.

**Comment by moritzbuck** [comment]
It seams like the pplacer package in bioconda is for Linux only, so manual install seams the right approach. You just have to remove the pplacer line in the environment.yaml and try again and it should work.

**Comment by suskraem** [comment]
Thanks, that worked great. However, I think I encountered the next Mac-specific issue. I'm running the test files provided and get the following error:
rule genesearch:
    input: MG01_tmp/MG01_counts.tsv
    output: MG01_outputs/MG01_hgcA_final.txt
    jobid: 0
    reason: Missing output files: MG01_outputs/MG01_hgcA_final.txt
    wildcards: sample=MG01
    resources: tmpdir=/var/folders/dn/m_jyj0ln73xgzyst87nw8p800000gp/T

sed: 1: "{1,2d}
": extra characters at the end of d command
awk: illegal primary in regular expression *$ at $
 source line number 1
 context is
	 >>> {{gsub(/*$/,"") <<< 

Error: Sequence file MG01_tmp/MG01_hgcA_proteins.faa is empty or misformatted

Uncaught exception: syntax error in MG01_tmp/MG01_hgcA_proteins.sto: didn't reach footer by EOF
Running pplacer v1.1.alpha17-6-g5cecf99 analysis on MG01_tmp/MG01_hgcA_proteins.sto...
Fatal error: exception Ppatteries.Sparse.Syntax_error("didn't reach footer by EOF", _)
Uncaught exception: Sqlite3.Error("table ranks already exists")
Fatal error: exception Sqlite3.Error("table ranks already exists")
Uncaught exception: Sys_error("MG01_tmp/MG01_hgcA_proteins.jplace: No such file or directory")
Fatal error: exception Sys_error("MG01_tmp/MG01_hgcA_proteins.jplace: No such file or directory")
Uncaught exception: Sys_error("MG01_tmp/MG01_hgcA_proteins.jplace: No such file or directory")
Fatal error: exception Sys_error("MG01_tmp/MG01_hgcA_proteins.jplace: No such file or directory")
Uncaught exception: Sys_error("MG01_tmp/MG01_hgcA_proteins.jplace: No such file or directory")
Fatal error: exception Sys_error("MG01_tmp/MG01_hgcA_proteins.jplace: No such file or directory")
sed: MG01_tmp/MG01_hgcA_classifications.csv: No such file or directory
awk: illegal primary in regular expression *$ at $
 source line number 1
 context is
	 >>> {gsub(/*$/,"") <<< 
awk: illegal primary in regular expression *$ at $
 source line number 1
 context is
	 >>> {{gsub(/*$/,"") <<< 
awk: illegal primary in regular expression *$ at $
 source line number 1
 context is
	 >>> {{gsub(/*$/,"") <<< 
head: illegal line count -- -3
head: illegal line count -- -3

**Comment by ericcapo** [comment]
Hi Susanne, is everything ok here so I can close this issue?
