### ISSUE TITLE
featureCounts error

### ISSUE THREAD

**Issue by suskraem** [ericcapo/marky-coco#2]
Hello,

I gave up on mac and am now running marky-coco on linux, so no urgent need to fix the previous issue. I just wanted to flag a bug I noticed. When running the example files I get the error shown below. I fixed it by changing the Snakefile a bit by adding the -p and the --countReadPairs (to avoid double counting) options to the featureCounts call. Just FYI.

Cheers!

ERROR: Paired-end reads were detected in single-end read library : MG01_tmp/MG01.bam

[Wed Sep  7 11:38:20 2022]

Error in rule featureCounts:

    jobid: 1

    output: MG01_tmp/MG01_counts.tsv

    shell:

        featureCounts -t CDS -o MG01_tmp/MG01_counts.tsv -g ID -a MG01_tmp/MG01_genes.gff MG01_tmp/MG01.bam

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by ericcapo** [comment]
Hi thank you very much for the feedbacks and sorry for the late reply (I am in parental leave for 3 weeks now). Can you please let me know if the bug mentioned above is with your tries in mac or with linux? This is not clear for me. I would be happy to modify the code that everyone can use it. Thank you in advance. Eric Capo

**Comment by suskraem** [comment]
Hello Eric, I'm very sorry to disturb you during your leave! I experienced this error using linux. It occurred to me that this might be an issue solely on my end, since I'm using subread v.2.0.3 (I couldn't use conda and made do with pre-installed components). So if you can't replicate the error it's most likely just that.

**Comment by ericcapo** [comment]
Do not apologize at all. I am so happy people are using this pipeline :). Hope everything is good now and you will get your hgcAB genes. Do not hesitate to contact me at eric.capo@hotmail.fr if you have questions about the data outputs. Cheers. Eric

**Comment by ericcapo** [comment]
To give a conclusion here, I modified the conda environment so it install the exact same version of the software I used. Hope this works better.
