### ISSUE TITLE
about advanced usage

### ISSUE THREAD

**Issue by ye00ye** [ericcapo/marky-coco#3]
Thanks for developing such a pipeline. 

I used its advadced usage with cleaned fastq files and existed final.contigs.fa, but  error appeared. So I want to ask if I want to use advanced usage, should I prepare all of  files listed in anvanced usage including sample.bam, sample_proteins.faa and coutns.tsv, besides cleaned fastq and contigs.

**Comment by ericcapo** [comment]
Hi, can you please send the error to see if I can locate which files is missing (or if the script is not properly written ;) ).
Thank you
Eric

**Comment by ye00ye** [comment]
Hello, now I want to ask another question. My index files were end up with .bt2l instead of .bt2 because my contigs file was too big, and the pipeline reported an error. though I still got the results, I want to ask whether or not there is some options I can choose to make the pipeline don't report error.
Thanks for your helping


| |
ye--ye
|
|
***@***.***
|
---- Replied Message ----
| From | Eric ***@***.***> |
| Date | 11/9/2022 16:12 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [ericcapo/marky-coco] about advanced usage (Issue #3) |

Hi, can you please send the error to see if I can locate which files is missing (or if the script is not properly written ;) ).
Thank you
Eric

**Comment by ericcapo** [comment]
This is unclear for me from what you wrote if the index files you are talking about come from marky-coco or that you want to bring them from outside. But if you bring them from outside, I think the easy way to make marky-coco to work, you can just modify the name extension. I have no clue how to make the pipeline not reporting an error about that, especially if you get the final outputs. Hope my answer helps.

**Comment by ye00ye** [comment]
Yes, I used advanced usage, and i used bowtie2 to build index, but contigs file is too big, so i got index files end with bt2l, please referring to the additional picture.


| |
ye--ye
|
|
***@***.***
|
---- Replied Message ----
| From | Eric ***@***.***> |
| Date | 11/10/2022 17:24 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [ericcapo/marky-coco] about advanced usage (Issue #3) |

This is unclear for me from what you wrote if the index files you are talking about come from marky-coco or that you want to bring them from outside. But if you bring them from outside, I think the easy way to make marky-coco to work, you can just modify the name extension. I have no clue how to make the pipeline not reporting an error about that, especially if you get the final outputs. Hope my answer helps.

**Comment by ericcapo** [comment]
sorry I do not see any picture. I do not understand what is the problem because you wrote "I still got the results". If this is only that the pipeline do not report the error (while still working), this is unfortunately out of my skills right now.

**Comment by ye00ye** [comment]
Usually, the index files end up with bt2, but if the index files are too big, it end up with bt2l, just like bowtie2 introduced in github as following: 


"bowtie2-build builds a Bowtie index from a set of DNA sequences. bowtie2-build outputs a set of 6 files with suffixes .1.bt2, .2.bt2, .3.bt2, .4.bt2, .rev.1.bt2, and .rev.2.bt2. In the case of a large index these suffixes will have a bt2l termination. These files together constitute the index: they are all that is needed to align reads to that reference. The original sequence FASTA files are no longer used by Bowtie 2 once the index is built."





But still thanks, it doesn't bring too many problems.




| |
ye--ye
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/10/2022 17:28 |
| To | ***@***.******@***.***> |
| Subject | Re: [ericcapo/marky-coco] about advanced usage (Issue #3) |
Yes, I used advanced usage, and i used bowtie2 to build index, but contigs file is too big, so i got index files end with bt2l, please referring to the additional picture.


| |
ye--ye
|
|
***@***.***
|
---- Replied Message ----
| From | Eric ***@***.***> |
| Date | 11/10/2022 17:24 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [ericcapo/marky-coco] about advanced usage (Issue #3) |

This is unclear for me from what you wrote if the index files you are talking about come from marky-coco or that you want to bring them from outside. But if you bring them from outside, I think the easy way to make marky-coco to work, you can just modify the name extension. I have no clue how to make the pipeline not reporting an error about that, especially if you get the final outputs. Hope my answer helps.
