### ISSUE TITLE
about OUTPUTS

### ISSUE THREAD

**Issue by ZhuoboLi** [ericcapo/marky-coco#5]
Hello,

I am trying to run your script to detect the hgcAB gene in some metagenomics samples, in the output result files hgcA_final.txt and hgcB_final.txt, why some genes only have gene id, the number of reads, gene length (bp), coverage values (nb of read/bp), but no amino acid sequences?

Thank you for you help.
best regards,
Bob

**Comment by ericcapo** [comment]
Hi Bob, thank your feedbacks. The error may be that I actually subset the wrong columns in the file {sample}_tmp/{sample}_hgcA_almost.txt. Do you find the information there?

If not, I re.worked a bit the script so I would suggest you delete your marky-coco folder, reinstall it (no need to resinstall the conda environment coco) and try again with the new script. If you get the same error, please send me the output final files and the slurm.out

**Comment by ericcapo** [comment]
Hi Bob, did you find the issue? If not, please note that I added a tutorial in marky-coco (the html file). Using it, you can follow step by step what is happening with the data. Hope this helps. Best, Eric

**Comment by ericcapo** [comment]
Hi Bob, another user may have found a way to overcome this issue. Could you please her version of the genesearch.sh file and check if this fix your issue? If yes please send an email to eric.capo@hotmail.fr and I will send you the doc. Cheers
Eric

**Comment by aljazdzy** [comment]
I am also having this issue, also I have a question about the phylogenetic tree output.  The tree is very large with a lot of organisms on it, but my hgcA hits are not, there are almost as many nodes on the tree as there are contigs.  How are these trees being generated?  Are they showing all the organisms that could have these genes?
